#!/usr/bin/env node
/**
 * Build `hooks/capture.mjs` from the published capture package.
 *
 * The hook has to run inside a plugin installation, which is a git clone with no
 * `node_modules`. So it cannot import anything: it is bundled to a single
 * self-contained file with no run-time resolution, no `npx`, and no network.
 *
 * The bundle is built from the **published** package at a pinned version rather
 * than from a working copy, so the committed artifact is reproducible from
 * public inputs and `--check` can prove it in CI. That check is the point — a
 * committed build output that nothing verifies is a build output that silently
 * goes stale.
 *
 *   node scripts/build-capture.mjs            # regenerate the bundle
 *   node scripts/build-capture.mjs --check    # fail if the committed bundle is stale
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The pinned package could not be fetched — as opposed to being fetched and
 * disagreeing with the committed bundle. The two need different outcomes, so
 * they need different types.
 */
class UnavailableError extends Error {}

/**
 * The published capture package, pinned exactly.
 *
 * Bump this to adopt new capture behavior, then rerun this script. A range would
 * make the committed bundle depend on when it was built, which defeats `--check`.
 *
 * NOTE: the SDK repo releases every package at one repo-wide version stamped
 * from the release tag, not at the placeholder in its `package.json`. So the
 * first published version of this package will be whatever the SDK's next
 * release is (0.16.x at time of writing), never `0.0.0-unpublished`. Set this to
 * that version once it exists — see `--check` below for what happens until then.
 */
const PACKAGE = "@introspection-sdk/coding-agent";
const VERSION = "0.0.0-unpublished";

/** Pinned so a bundler release cannot silently change the committed artifact. */
const ESBUILD = "esbuild@0.27.7";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(root, "hooks", "capture.mjs");

// No shebang here: esbuild preserves the entry's own `#!/usr/bin/env node` and
// emits it before the banner. Adding one produces a second shebang on line 2,
// which is a hard syntax error rather than a stray comment.
const BANNER = [
  `// Generated by scripts/build-capture.mjs from ${PACKAGE}@${VERSION}. Do not edit.`,
  // The OTLP exporter's dependencies reach for `require` at load time. An ESM
  // bundle has none, so one is constructed from the module URL.
  "import{createRequire}from'node:module';const require=createRequire(import.meta.url);",
].join("\n");

function build(destination) {
  const staging = mkdtempSync(join(tmpdir(), "introspection-capture-build-"));
  try {
    writeFileSync(
      join(staging, "package.json"),
      JSON.stringify({ name: "capture-build", private: true, type: "module" }),
    );

    try {
      // Not `--silent`: when this fails, npm's own message is the useful part,
      // and suppressing it leaves a bare non-zero exit to explain itself.
      execFileSync(
        "npm",
        ["install", "--no-audit", "--no-fund", `${PACKAGE}@${VERSION}`],
        { cwd: staging, stdio: "inherit" },
      );
    } catch {
      throw new UnavailableError(
        `${PACKAGE}@${VERSION} could not be installed from npm.`,
      );
    }

    // The package's own bin is the hook entrypoint, so bundling it gives the
    // exact surface the hook invokes rather than a re-implementation.
    const entry = join(staging, "node_modules", PACKAGE, "dist", "bin.js");
    if (!existsSync(entry)) {
      throw new Error(`${PACKAGE}@${VERSION} did not provide dist/bin.js`);
    }

    execFileSync(
      "npx",
      [
        "--yes",
        ESBUILD,
        entry,
        "--bundle",
        "--platform=node",
        "--target=node22",
        "--format=esm",
        "--minify",
        "--legal-comments=none",
        `--outfile=${destination}`,
        `--banner:js=${BANNER}`,
      ],
      { cwd: staging, stdio: "inherit" },
    );
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

const check = process.argv.includes("--check");

if (!check) {
  build(outputPath);
  const bytes = readFileSync(outputPath).length;
  console.log(`Wrote hooks/capture.mjs (${(bytes / 1024).toFixed(0)} KB)`);
  process.exit(0);
}

if (!existsSync(outputPath)) {
  console.error("hooks/capture.mjs is missing. Run: node scripts/build-capture.mjs");
  process.exit(1);
}

const candidate = join(mkdtempSync(join(tmpdir(), "introspection-capture-check-")), "capture.mjs");

try {
  build(candidate);
} catch (error) {
  if (!(error instanceof UnavailableError)) throw error;
  // The pin is not on npm yet. This is the expected state until the SDK
  // publishes, and it is NOT a stale bundle: "stale" only means anything once
  // there is a published source of truth to be stale against. Failing here
  // would leave a permanently red check that trains people to ignore CI, so
  // this reports loudly and passes — and goes back to failing hard the moment
  // the pin resolves and disagrees.
  console.error(`SKIPPED: ${error.message}`);
  console.error(
    "The committed hooks/capture.mjs is therefore UNVERIFIED. Set VERSION in\n" +
      "this script to the first published release and re-run to enforce it.",
  );
  process.exit(0);
}

const committed = readFileSync(outputPath);
const rebuilt = readFileSync(candidate);

if (!committed.equals(rebuilt)) {
  console.error(
    `hooks/capture.mjs does not match ${PACKAGE}@${VERSION}.\n` +
      "Run: node scripts/build-capture.mjs — and commit the result.",
  );
  process.exit(1);
}

console.log(`hooks/capture.mjs matches ${PACKAGE}@${VERSION}`);
