#!/usr/bin/env node
/**
 * Build `hooks/capture.mjs` from the published capture package.
 *
 * The hook has to run inside a plugin installation, which is a git clone with no
 * `node_modules`. So it cannot import anything: it is bundled to a single
 * self-contained file with no run-time resolution, no `npx`, and no network.
 *
 * The bundle is built from the **published** package at a pinned version rather
 * than from a working copy, so the committed artifact is reproducible from
 * public inputs and `--check` can prove it in CI. That check is the point — a
 * committed build output that nothing verifies is a build output that silently
 * goes stale.
 *
 *   node scripts/build-capture.mjs            # regenerate the bundle
 *   node scripts/build-capture.mjs --check    # fail if the committed bundle is stale
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The published capture package, pinned exactly.
 *
 * Bump this to adopt new capture behavior, then rerun this script. A range would
 * make the committed bundle depend on when it was built, which defeats `--check`.
 */
const PACKAGE = "@introspection-sdk/coding-agent";
const VERSION = "0.1.0";

/** Pinned so a bundler release cannot silently change the committed artifact. */
const ESBUILD = "esbuild@0.27.7";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(root, "hooks", "capture.mjs");

// No shebang here: esbuild preserves the entry's own `#!/usr/bin/env node` and
// emits it before the banner. Adding one produces a second shebang on line 2,
// which is a hard syntax error rather than a stray comment.
const BANNER = [
  `// Generated by scripts/build-capture.mjs from ${PACKAGE}@${VERSION}. Do not edit.`,
  // The OTLP exporter's dependencies reach for `require` at load time. An ESM
  // bundle has none, so one is constructed from the module URL.
  "import{createRequire}from'node:module';const require=createRequire(import.meta.url);",
].join("\n");

function build(destination) {
  const staging = mkdtempSync(join(tmpdir(), "introspection-capture-build-"));
  try {
    writeFileSync(
      join(staging, "package.json"),
      JSON.stringify({ name: "capture-build", private: true, type: "module" }),
    );

    execFileSync(
      "npm",
      ["install", "--no-audit", "--no-fund", "--silent", `${PACKAGE}@${VERSION}`],
      { cwd: staging, stdio: "inherit" },
    );

    // The package's own bin is the hook entrypoint, so bundling it gives the
    // exact surface the hook invokes rather than a re-implementation.
    const entry = join(staging, "node_modules", PACKAGE, "dist", "bin.js");
    if (!existsSync(entry)) {
      throw new Error(`${PACKAGE}@${VERSION} did not provide dist/bin.js`);
    }

    execFileSync(
      "npx",
      [
        "--yes",
        ESBUILD,
        entry,
        "--bundle",
        "--platform=node",
        "--target=node22",
        "--format=esm",
        "--minify",
        "--legal-comments=none",
        `--outfile=${destination}`,
        `--banner:js=${BANNER}`,
      ],
      { cwd: staging, stdio: "inherit" },
    );
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

const check = process.argv.includes("--check");

if (!check) {
  build(outputPath);
  const bytes = readFileSync(outputPath).length;
  console.log(`Wrote hooks/capture.mjs (${(bytes / 1024).toFixed(0)} KB)`);
  process.exit(0);
}

if (!existsSync(outputPath)) {
  console.error("hooks/capture.mjs is missing. Run: node scripts/build-capture.mjs");
  process.exit(1);
}

const candidate = join(mkdtempSync(join(tmpdir(), "introspection-capture-check-")), "capture.mjs");
build(candidate);

const committed = readFileSync(outputPath);
const rebuilt = readFileSync(candidate);

if (!committed.equals(rebuilt)) {
  console.error(
    `hooks/capture.mjs does not match ${PACKAGE}@${VERSION}.\n` +
      "Run: node scripts/build-capture.mjs — and commit the result.",
  );
  process.exit(1);
}

console.log(`hooks/capture.mjs matches ${PACKAGE}@${VERSION}`);
