#!/usr/bin/env node
/**
 * Build `hooks/capture.mjs` from the published capture package.
 *
 * The hook has to run inside a plugin installation, which is a git clone with no
 * `node_modules`. So it cannot import anything: it is bundled to a single
 * self-contained file with no run-time resolution, no `npx`, and no network.
 *
 * The bundle is built from the **published** package at a pinned version rather
 * than from a working copy, so the committed artifact is reproducible from
 * public inputs and `--check` can prove it in CI. That check is the point — a
 * committed build output that nothing verifies is a build output that silently
 * goes stale.
 *
 *   node scripts/build-capture.mjs            # regenerate from the published pin
 *   node scripts/build-capture.mjs --check    # fail if the committed bundle is stale
 *   node scripts/build-capture.mjs --local-sdk=/path/to/introspection-js-sdk
 *                                             # explicit local test artifact
 */
import { execFileSync } from "node:child_process";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
  existsSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The pinned package could not be fetched — as opposed to being fetched and
 * disagreeing with the committed bundle. The two need different outcomes, so
 * they need different types.
 */
class UnavailableError extends Error {}

/**
 * The published capture package, pinned exactly.
 *
 * Bump this to adopt new capture behavior, then rerun this script. A range would
 * make the committed bundle depend on when it was built, which defeats `--check`.
 *
 * The SDK repo releases every package at one repo-wide version stamped from the
 * release tag rather than the placeholder in its source `package.json`.
 */
const PACKAGE = "@introspection-sdk/coding-agent";
const VERSION = "0.17.0";

/** Pinned so a bundler release cannot silently change the committed artifact. */
const ESBUILD = "esbuild@0.27.7";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(root, "hooks", "capture.mjs");

// No shebang here: esbuild preserves the entry's own `#!/usr/bin/env node` and
// emits it before the banner. Adding one produces a second shebang on line 2,
// which is a hard syntax error rather than a stray comment.
function banner(source) {
  return [
    `// Generated by scripts/build-capture.mjs from ${source}. Do not edit.`,
    // The OTLP exporter's dependencies reach for `require` at load time. An ESM
    // bundle has none, so one is constructed from the module URL.
    "import{createRequire}from'node:module';const require=createRequire(import.meta.url);",
  ].join("\n");
}

function build(destination, localSdk) {
  const staging = mkdtempSync(join(tmpdir(), "introspection-capture-build-"));
  try {
    writeFileSync(
      join(staging, "package.json"),
      JSON.stringify({ name: "capture-build", private: true, type: "module" }),
    );

    let entry;
    let source;
    if (localSdk) {
      entry = resolve(
        localSdk,
        "packages",
        "introspection-coding-agent",
        "dist",
        "bin.js",
      );
      source = `${PACKAGE} local checkout (development artifact)`;
    } else {
      try {
        // Not `--silent`: when this fails, npm's own message is the useful part,
        // and suppressing it leaves a bare non-zero exit to explain itself.
        execFileSync(
          "npm",
          ["install", "--no-audit", "--no-fund", `${PACKAGE}@${VERSION}`],
          { cwd: staging, stdio: "inherit" },
        );
      } catch {
        throw new UnavailableError(
          `${PACKAGE}@${VERSION} could not be installed from npm.`,
        );
      }
      // The package's own bin is the hook entrypoint, so bundling it gives the
      // exact surface the hook invokes rather than a re-implementation.
      entry = join(staging, "node_modules", PACKAGE, "dist", "bin.js");
      source = `${PACKAGE}@${VERSION}`;
    }
    if (!existsSync(entry)) {
      throw new Error(`${source} did not provide dist/bin.js; build it first`);
    }

    execFileSync(
      "npx",
      [
        "--yes",
        ESBUILD,
        entry,
        "--bundle",
        "--platform=node",
        "--target=node22",
        "--format=esm",
        "--minify",
        "--legal-comments=none",
        `--outfile=${destination}`,
        `--banner:js=${banner(source)}`,
      ],
      { cwd: staging, stdio: "inherit" },
    );
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

const check = process.argv.includes("--check");
const localSdkArgument = process.argv.find((argument) =>
  argument.startsWith("--local-sdk="),
);
const localSdk = localSdkArgument?.slice("--local-sdk=".length);
const verificationSource = localSdk
  ? `${PACKAGE} local checkout (development artifact)`
  : `${PACKAGE}@${VERSION}`;

if (!check) {
  build(outputPath, localSdk);
  const bytes = readFileSync(outputPath).length;
  console.log(`Wrote hooks/capture.mjs (${(bytes / 1024).toFixed(0)} KB)`);
  process.exit(0);
}

if (!existsSync(outputPath)) {
  console.error(
    "hooks/capture.mjs is missing. Run: node scripts/build-capture.mjs",
  );
  process.exit(1);
}

const candidate = join(
  mkdtempSync(join(tmpdir(), "introspection-capture-check-")),
  "capture.mjs",
);

try {
  build(candidate, localSdk);
} catch (error) {
  if (!(error instanceof UnavailableError)) throw error;
  console.error(`FAILED: ${error.message}`);
  console.error(
    "The committed hooks/capture.mjs could not be verified. Publish the pinned\n" +
      "SDK version or use --local-sdk explicitly for local development only.",
  );
  process.exit(1);
}

const committed = readFileSync(outputPath);
const rebuilt = readFileSync(candidate);

if (!committed.equals(rebuilt)) {
  console.error(
    `hooks/capture.mjs does not match ${verificationSource}.\n` +
      "Run: node scripts/build-capture.mjs — and commit the result.",
  );
  process.exit(1);
}

console.log(`hooks/capture.mjs matches ${verificationSource}`);
